In [1]:
import numpy as np
import pandas as pd

In [4]:
#将模糊判别矩阵转化为模糊一致矩阵的函数
def transform(R):
    #将R的每一行求和
    sum_R=np.sum(R,axis=1)
    #R的维度
    dim_R=R.shape[0]
    for i in range(dim_R):
        for j in range(dim_R):
            R[i][j]=(sum_R[i]-sum_R[j])/(2*dim_R)+0.5
    return R

[[0.5 0.4]
 [0.6 0.5]]


In [9]:
def check(R):
    #R的维度
    dim_R=R.shape[0]
    for i in range(dim_R):
        for j in range(dim_R):
            if R[i][j]+R[j][i]!=1:
                return False
    return True

In [10]:
R1=np.array([[0.5,0.4],[0.6,0.5]])
check(R1)

True

In [11]:
R21 = np.array([[0.5, 0.3, 0.2, 0.5, 0.2, 0.3, 0.4], [0.7, 0.5, 0.4, 0.7, 0.4, 0.5, 0.6], [0.8, 0.6, 0.5, 0.8, 0.5, 0.6, 0.7],
    [0.5, 0.3, 0.2, 0.5, 0.2, 0.3, 0.4], [0.8, 0.6, 0.5, 0.8, 0.5, 0.6, 0.7], [0.7, 0.5, 0.4, 0.7, 0.4, 0.5, 0.6],
    [0.6, 0.4, 0.3, 0.6, 0.3, 0.4, 0.5]])
check(R21)

True

In [13]:
R21=np.transpose(R21)
R21

array([[0.5, 0.7, 0.8, 0.5, 0.8, 0.7, 0.6],
       [0.3, 0.5, 0.6, 0.3, 0.6, 0.5, 0.4],
       [0.2, 0.4, 0.5, 0.2, 0.5, 0.4, 0.3],
       [0.5, 0.7, 0.8, 0.5, 0.8, 0.7, 0.6],
       [0.2, 0.4, 0.5, 0.2, 0.5, 0.4, 0.3],
       [0.3, 0.5, 0.6, 0.3, 0.6, 0.5, 0.4],
       [0.4, 0.6, 0.7, 0.4, 0.7, 0.6, 0.5]])

In [14]:
print(transform(R21))

[[0.5  0.6  0.65 0.5  0.65 0.6  0.55]
 [0.4  0.5  0.55 0.4  0.55 0.5  0.45]
 [0.35 0.45 0.5  0.35 0.5  0.45 0.4 ]
 [0.5  0.6  0.65 0.5  0.65 0.6  0.55]
 [0.35 0.45 0.5  0.35 0.5  0.45 0.4 ]
 [0.4  0.5  0.55 0.4  0.55 0.5  0.45]
 [0.45 0.55 0.6  0.45 0.6  0.55 0.5 ]]


In [15]:
def get_weight(R):
    #R的维度
    dim_R=R.shape[0]
    #将R的每一行求和
    sum_R=np.sum(R,axis=1)
    w=np.zeros(dim_R)
    n=dim_R
    alpha=(n-1)/2
    for i in range(dim_R):
        w[i]=1/n-1/(2*alpha)+1/(n*alpha)*sum_R[i]
    return w
R1=np.array([[0.5,0.4],[0.6,0.5]])
print(get_weight(R1))

[0.4 0.6]


In [17]:
R21 = np.array([[0.5, 0.3, 0.2, 0.5, 0.2, 0.3, 0.4], [0.7, 0.5, 0.4, 0.7, 0.4, 0.5, 0.6], [0.8, 0.6, 0.5, 0.8, 0.5, 0.6, 0.7],
    [0.5, 0.3, 0.2, 0.5, 0.2, 0.3, 0.4], [0.8, 0.6, 0.5, 0.8, 0.5, 0.6, 0.7], [0.7, 0.5, 0.4, 0.7, 0.4, 0.5, 0.6],
    [0.6, 0.4, 0.3, 0.6, 0.3, 0.4, 0.5]])
R21=np.transpose(R21)
print(transform(R21))
R21=get_weight(transform(R21))
print(R21)

[[0.5  0.6  0.65 0.5  0.65 0.6  0.55]
 [0.4  0.5  0.55 0.4  0.55 0.5  0.45]
 [0.35 0.45 0.5  0.35 0.5  0.45 0.4 ]
 [0.5  0.6  0.65 0.5  0.65 0.6  0.55]
 [0.35 0.45 0.5  0.35 0.5  0.45 0.4 ]
 [0.4  0.5  0.55 0.4  0.55 0.5  0.45]
 [0.45 0.55 0.6  0.45 0.6  0.55 0.5 ]]
[0.15595238 0.13928571 0.13095238 0.15595238 0.13095238 0.13928571
 0.14761905]
